# Generated by Django 5.1 on 2024-08-17 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Введите Ваше имя полностью в формате ФИО",
                        max_length=100,
                        verbose_name="Ваше ФИО",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        help_text="Укажите Вашу должность",
                        max_length=100,
                        verbose_name="Должность",
                    ),
                ),
                (
                    "vacation_status",
                    models.BooleanField(
                        default=False, verbose_name="Статус сотрудника"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_name",
                    models.CharField(max_length=100, verbose_name="Название задачи"),
                ),
                (
                    "start_date",
                    models.DateField(verbose_name="Дата начала выполнения задачи"),
                ),
                (
                    "end_date",
                    models.DateField(verbose_name="Дата завершения выполнения задачи"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("done", "Выполнено"),
                            ("in_progress", "В процессе"),
                            ("not_started", "Не начато"),
                        ],
                        default="not_started",
                        max_length=50,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, null=True, verbose_name="Комментарий к задаче"
                    ),
                ),
                (
                    "owner",
                    models.TextField(blank=True, null=True, verbose_name="Создатель"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Признак активности задачи"
                    ),
                ),
                (
                    "is_important",
                    models.BooleanField(
                        default=False, verbose_name="Признак важности задачи"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tasks.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tasks.task",
                        verbose_name="Родительская задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
    ]
